=== consultant-1379/onetwork/onetwork-jar/src/main/resources/schema/MomParserConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="MomParserConfig">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="platformType" type="xs:string"></xs:element>
        <xs:element name="nodeType" type="xs:string"></xs:element>
        <xs:element name="input">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="mpDtdURI" type="xs:string"></xs:element>
              <xs:element name="momURI" type="xs:string">
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="output">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="momPool" type="xs:string"></xs:element>
              <xs:element name="version" type="xs:string"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== consultant-1379/onetwork/onetwork-jar/src/main/resources/bs/nrms/ecim_SGSN.xml
<?xml version="1.0" encoding="UTF-8"?>
<MomParserConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/MomParserConfig.xsd">
  <platformType>ecim</platformType>
  <nodeType>sgsn</nodeType>
  <input>
    <mpDtdURI>./src/main/resources/schema/mp.dtd</mpDtdURI>
    <momURI>./src/main/resources/sgsn_nodes/SGSN_15B-WPP-V5</momURI>
  </input>
  <output>
    <momPool>./target/outdir</momPool>
    <version>v5</version>
  </output>
</MomParserConfig>
